### ISSUE TITLE
Error while calling lua chunk: init.lua:30 attempt to index field 'bo' (a nil value)

### ISSUE THREAD

**Issue by csierra** [gennaro-tedesco/nvim-jqix#19]
hi! getting this in neovim in Ubuntu 20.04... installed nvim-jqx via Plug

**Comment by gennaro-tedesco** [comment]
Good evening! Let us try to reproduce the problem: in particular 

1. what version of neovim are you on?
2. do you have `jq` installed on your computer?
3. can you provide a minimally reproduced example file where you are getting such error?

You can find a [test.json](https://github.com/gennaro-tedesco/nvim-jqx/blob/master/examples/test.json) here to test it out: does it work in that case?

**Comment by csierra** [comment]
hey @gennaro-tedesco:

1. 
```
nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compilado por team+vim@tracker.debian.org
```
2.
```
jq --version
jq-1.6
```
3. Tested with `test.json` and getting the same error. 

Versions are those that come default with Ubuntu 20.04 as far as I know...

Thanks a lot for this package and for your support!

**Comment by csierra** [comment]
hi again...
I upgraded to nvim 0.6 using snap instead of ubuntu package and I confirm it works now...

**Comment by gennaro-tedesco** [comment]
```
nvim --version
NVIM v0.4.3
```
this plugin is supposed to work with `nvim > 0.5`: the error you are getting is because the option `vim.bo` in [this line](https://github.com/gennaro-tedesco/nvim-jqx/blob/03b678e5cb293d0e952a649fce3cdba02424bf57/lua/nvim-jqx/init.lua#L30) was introduced in `v0.5`. Therefore please update your neovim version to the latest (or 0.5 at least) and try again.

P. S. most latest neovim plugins require > 0.5, so you _will_ have to upgrade it sooner or later anyway :)

**Comment by csierra** [comment]
Thanks a lot Gennaro! I will close the issue now...
